
# Iniciando um Banco de dados MongoDB em um container Docker

version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always # iniciar com o servidor
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo_vol:/docker/mongo

    networks:
    - backend   
    
  mongo-express:
    image: mongo-express:latest
    container_name: 'MongoExpress'
    restart: always # iniciar com o servidor
    ports:
      - 8081:8081
    depends_on:
      - database
    environment:    
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017/
    networks:
      - backend
      
  app:
      # Configuration for building the docker image for the service
      build:
        context: . # Use an image built from the specified dockerfile in the current directory.
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
      - 5000:5000    
      depends_on: 
        - database # This service depends on redis. Start that first.
      environment: # Pass environment variables to the service
        MONGODB_DB: $MONGODB_DB
        MONGODB_HOST: $MONGODB_HOST
        MONGODB_PORT: $MONGODB_PORT
        MONGODB_USERNAME: $MONGODB_USERNAME
        MONGODB_PASSWORD: $MONGODB_PASSWORD


      networks: # Networks to join (Services on the same network can communicate with each other using their name)
        - backend
networks: 
    backend:
      driver: bridge  

volumes:
  mongo_vol: